[project]
name = "bedrock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "musfirofficial", email = "musfirofficial@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
]

[project.scripts]
bedrock = "bedrock:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
